/**
 * Inspection marker + finding domain models.
 *
 * Desired flow (per the approved Sales Brain workflow):
 *
 *   BugMan Graph -> Inspection Markers -> Inspection Findings
 *     -> BugMan Intelligence -> Recommended Service -> Customer Report
 *
 * `InspectionMarker` mirrors `GraphAnnotation` from BugManInspects
 * (lib/models/graph_annotation.dart) closely enough that a marker placed on
 * a graph can be read here without re-entering data. `MarkerCategory` and
 * `MarkerSymbol` mirror `GraphMarkerCategory` / `GraphMarkerSymbol`.
 *
 * `InspectionFinding` is a Sales Brain concept: a homeowner-facing writeup
 * derived from one or more markers. Findings are what technicians review and
 * approve -- BugMan Intelligence may polish wording, but a finding always
 * traces back to the marker(s) it came from via `markerIds`.
 */

/** Mirrors BugManInspects' GraphMarkerCategory enum (graph_annotation.dart). */
export type MarkerCategory =
  | "insectFindings"
  | "structureFindings"
  | "moistureFindings"
  | "structureDetails"
  | "treatment"
  | "review";

/**
 * Mirrors BugManInspects' GraphMarkerType enum. Kept as a plain string union
 * (not a hardcoded finite list) because BugMan Graphs owns the canonical
 * marker catalog (lib/models/graph_marker_catalog.dart) and adds types over
 * time -- Sales Brain should treat unrecognized values as valid pass-through
 * data rather than rejecting them.
 */
export type MarkerType = string;

export type FindingSeverity = "low" | "medium" | "high" | "critical";

/**
 * A single marker placed on a BugMan Graph. This is intentionally close to
 * GraphAnnotation's JSON shape (id, kind, point, label, markerType, note,
 * attachmentIds) so the adapter in services/bugmanGraphs can map 1:1 without
 * lossy translation.
 */
export interface InspectionMarker {
  id: string;
  type: MarkerType;
  category: MarkerCategory;
  title: string;
  /** Free-form area/room label, e.g. "South crawlspace", "Utility room". */
  area?: string;
  /** Reference back to the source graph, e.g. `${graphId}#${annotationId}`. */
  graphRef: {
    graphId: string;
    annotationId: string;
  };
  observation: string;
  /**
   * Not yet a first-class field on GraphAnnotation upstream. Until BugMan
   * Graphs adds it, technicians may set it here and it round-trips through
   * GraphAnnotation.extraProperties so it isn't lost on save/reload.
   */
  severity?: FindingSeverity;
  measurements?: Record<string, number | string>;
  notes?: string;
  photoIds: string[];
  createdBy: string;
  createdAt: string;
}

export type FindingStatus = "pending_review" | "approved" | "rejected";

/**
 * A homeowner-facing finding. Reviewed and approved by a human in the
 * Inspection Findings step -- never auto-approved by BugMan Intelligence.
 */
export interface InspectionFinding {
  id: string;
  /** Graph-derived observations and technician notes must not overwrite each other. */
  source?: "graph" | "custom" | "legacy";
  sourceGraphKey?: string;
  /** Canonical BugMan Graphs marker type used for one-card-per-type grouping. */
  markerType?: MarkerType;
  /** Prevents a later graph refresh from replacing technician edits. */
  userEdited?: boolean;
  /** Hidden findings retain their technician edits and return unchanged when reselected. */
  hidden?: boolean;
  /** Customer-facing by default; staff can explicitly hide a finding from reports. */
  customerVisible?: boolean;
  title: string;
  /** Homeowner-facing description. May start as the marker observation verbatim. */
  summary: string;
  category: MarkerCategory;
  severity?: FindingSeverity;
  tag: string;
  /** Every marker this finding was derived from. Empty only for manually authored findings. */
  markerIds: string[];
  photoIds: string[];
  status: FindingStatus;
  /** Set once BugMan Intelligence has polished the wording; see BugManIntelligenceService.polishFinding. */
  polishedByIntelligence?: boolean;
  /**
   * Homeowner-facing rewording generated by BugMan Intelligence, kept
   * separate from `summary` (the technician's original observation) so the
   * UI can always show both -- never a silent replacement. Undefined until
   * a human explicitly requests it via BugManIntelligenceService.polishFinding.
   */
  customerFacingSummary?: string;
  createdAt: string;
  updatedAt: string;
}
